// scripts/build-help.ts
//
// Convert every Markdown document under oosd/docs/help/ into a
// generated TypeScript module that exports them as plain string
// constants. The HelpPanel imports the generated module directly,
// which avoids two failure modes that hit the runtime-fetch path:
//
//   1. Electrobun's `views://` custom scheme does not always serve
//      .md files cleanly, so `fetch("./help/...")` from a renderer
//      sometimes failed with no recoverable error.
//   2. Shipping documentation as bundle assets meant `widgets.md`
//      had to be copied into the .app and watched separately. As a
//      generated TS module, the docs travel with the source and
//      are picked up by the same bundler pass as the React code.
//
// Running this script is cheap (file IO + a string concat) and is
// wired into `predev` / `prebuild` so authors only edit Markdown.
//
// Usage:  bun run scripts/build-help.ts
//   or:   bun run help:build

import {
	readFileSync,
	readdirSync,
	mkdirSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";

// ─── Paths ───────────────────────────────────────────────────────────

const REPO_ROOT  = resolve(import.meta.dir, "..");
const SOURCE_DIR = join(REPO_ROOT, "docs", "help");
const OUT_FILE   = join(
	REPO_ROOT,
	"src",
	"mainview",
	"components",
	"help",
	"help-content.generated.ts",
);

// ─── Read every .md file in the source directory ─────────────────────
//
// Files are picked up alphabetically and keyed by their basename
// without extension. The `index.md` topic, if present, is treated
// like any other — the HelpPanel decides which one to show first.

type Entry = { id: string; file: string; content: string };

const entries: Entry[] = readdirSync(SOURCE_DIR)
	.filter((f) => f.endsWith(".md"))
	.sort()
	.map((file) => {
		const id      = file.replace(/\.md$/, "");
		const content = readFileSync(join(SOURCE_DIR, file), "utf8");
		return { id, file, content };
	});

if (entries.length === 0) {
	console.error(`no .md files found under ${SOURCE_DIR}`);
	process.exit(1);
}

// ─── Emit a TypeScript module ────────────────────────────────────────
//
// Each entry becomes one named export plus a default record map.
// Backticks inside the Markdown have to be escaped because the
// generated module wraps every body in a template literal. Backslash
// and ${ also need escaping for the same reason.

function escapeForTemplate(s: string): string {
	return s
		.replace(/\\/g, "\\\\")
		.replace(/`/g, "\\`")
		.replace(/\$\{/g, "\\${");
}

const header = `// help-content.generated.ts
//
// AUTO-GENERATED by scripts/build-help.ts — do not edit by hand.
// Edit the source Markdown under docs/help/ and re-run the script
// (or just \`bun run dev\`, which calls it via predev).

`;

const exports = entries
	.map(
		(e) =>
			`export const ${tsIdent(e.id)} = \`${escapeForTemplate(e.content)}\`;`,
	)
	.join("\n\n");

const map = `\nexport const helpContent: Record<string, string> = {\n${entries
	.map((e) => `\t${JSON.stringify(e.id)}: ${tsIdent(e.id)},`)
	.join("\n")}\n};\n`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, header + exports + map);

console.log(`wrote ${OUT_FILE}  (${entries.length} topic(s))`);
for (const e of entries) {
	console.log(`  - ${e.id}  ${e.content.length} bytes`);
}

// ─── Helpers ─────────────────────────────────────────────────────────

// Convert a kebab- or snake-cased filename into a valid TS identifier
// for the `export const NAME = ...` form. The map exposes the original
// id either way, so this is just for the per-file constant name.
function tsIdent(id: string): string {
	const cleaned = id.replace(/[^A-Za-z0-9_]/g, "_");
	return /^[A-Za-z_]/.test(cleaned) ? cleaned : `_${cleaned}`;
}
