package seed

// police.go — Demo police events for the local development seed.
//
// Contains two fictional police cases with realistic event streams.
// Events are stored in oos.events via PostgreSQL directly.
// Embeddings are generated by the Ollama embedding endpoint at seed time.
//
// Cases:
//   fall-2024-0042  — Burglary at Industriestrasse Munich
//   fall-2024-0080  — Parrot escape and café occupation Augsburg

// PoliceEvent is a fictional police incident event used for seeding.
type PoliceEvent struct {
	Stream    string
	EventType string
	Text      string
	Payload   string
}

// Fall0042Events contains the event stream for the Munich burglary case.
var Fall0042Events = []PoliceEvent{
	{
		Stream:    "fall-2024-0042",
		EventType: "EinsatzAusgeloest",
		Text:      "Alarm ausgeloest durch Einbruchmeldeanlage um 02:00 Uhr. Zwei Streifenwagen entsandt.",
		Payload:   `{"adresse":"Industriestrasse 17, 80939 Muenchen","einsatz_nr":"E-2024-8821"}`,
	},
	{
		Stream:    "fall-2024-0042",
		EventType: "TatortGesichert",
		Text:      "Osteingang aufgebrochen. Hebelspuren am Tuerrahmen. Glasscherben innen. Kein Taeter vor Ort.",
		Payload:   `{"bereich":"Lagerhalle Osteingang"}`,
	},
	{
		Stream:    "fall-2024-0042",
		EventType: "SpurSichergestellt",
		Text:      "Reifenabdruck auf unbefestigtem Untergrund. Breite ca. 225mm, typisch fuer Transporter.",
		Payload:   `{"spur_typ":"Reifenabdruck","fundort":"Parkplatz Suedseite"}`,
	},
	{
		Stream:    "fall-2024-0042",
		EventType: "ZeugenAussageAufgenommen",
		Text:      "Nachbar Rudolf K. hoerte gegen 02:15 Uhr Motorengeraeusche. Sah weissen Transporter ohne Aufschrift. Fuhr ca. 02:45 Uhr Richtung Nordausfahrt.",
		Payload:   `{"zeuge_id":"Z-001","relation":"Nachbar"}`,
	},
	{
		Stream:    "fall-2024-0042",
		EventType: "ZeugenAussageAufgenommen",
		Text:      "Sicherheitsdienstmitarbeiter Thomas W. sah weissen Transporter mit getoenten Scheiben. Teilkennzeichen: M-?? 4??.",
		Payload:   `{"zeuge_id":"Z-002","relation":"Sicherheitsdienst"}`,
	},
	{
		Stream:    "fall-2024-0042",
		EventType: "SpurSichergestellt",
		Text:      "Hebelwerkzeug hinterliess Abdruck am Tuerrahmen. Breite ca. 30mm. Kriminaltechniker angefordert.",
		Payload:   `{"spur_typ":"Werkzeugabdruck","fundort":"Tuerrahmen Osteingang"}`,
	},
}

// Fall0080Events contains the event stream for the Augsburg zoo parrot escape case.
//
// A breeding pair of African grey parrots escaped from Augsburg Zoo and
// occupied the pastry counter of a nearby café. The case structurally
// mirrors a hostage situation (perpetrators, witnesses, negotiation,
// evidence, peaceful resolution) but keeps the demo tone light.
var Fall0080Events = []PoliceEvent{
	{
		Stream:    "fall-2024-0080",
		EventType: "EinsatzAusgeloest",
		Text:      "Notruf um 09:14 Uhr. Zwei ausgebuexte Graupapageien aus dem Augsburger Zoo haben die Theke des Cafe Kolibri in der Maximilianstrasse 42 besetzt. Vier Gaeste und eine Baeckerin kommen nicht mehr an ihre Croissants.",
		Payload:   `{"adresse":"Maximilianstrasse 42, 86150 Augsburg","einsatz_nr":"E-2024-3301","betroffene_gaeste":4}`,
	},
	{
		Stream:    "fall-2024-0080",
		EventType: "TaeterBeschreibung",
		Text:      "Taeter 1: Graupapagei, ca. 33cm, Rufname Coco, auffaelliger roter Schwanz, ruft unablaessig Freiheit. Taeter 2: Graupapagei, ca. 31cm, Rufname Pepe, etwas kleiner, imitiert Kaffeemaschine und Handyklingeln.",
		Payload:   `{"anzahl_taeter":2,"spezies":"Psittacus erithacus","herkunft":"Zoo Augsburg Voliere 7"}`,
	},
	{
		Stream:    "fall-2024-0080",
		EventType: "VerhandlungAufgenommen",
		Text:      "Tierpfleger Bernd Moeller vom Augsburger Zoo uebernimmt die Verhandlung. Taeter fordern Sonnenblumenkerne und ungestoerten Zugang zur Croissant-Auslage. Forderungsfrist bis 12:00 Uhr, sonst drohen weitere Imitationen der Kaffeemaschine.",
		Payload:   `{"verhandlungsfuehrer":"Tierpfleger Bernd Moeller","forderung":"Sonnenblumenkerne + Croissants","frist":"12:00"}`,
	},
	{
		Stream:    "fall-2024-0080",
		EventType: "ZeugenAussageAufgenommen",
		Text:      "Passantin Maria S. beobachtete die beiden Papageien beim Anflug aus Richtung Stadtpark. Coco landete zuerst auf der Espressomaschine, Pepe folgte ueber das offene Oberlicht.",
		Payload:   `{"zeuge_id":"Z-001","relation":"Passantin","anflugrichtung":"Stadtpark"}`,
	},
	{
		Stream:    "fall-2024-0080",
		EventType: "SpurSichergestellt",
		Text:      "Mehrere graue Schwanzfedern und ein angeknabbertes Butter-Croissant sichergestellt. Federn zur DNA-Abgleichung an die Zoo-Tieraerztin uebergeben.",
		Payload:   `{"spur_typ":"Federn, Croissant","fundort":"Theke und Oberlicht Cafe Kolibri"}`,
	},
	{
		Stream:    "fall-2024-0080",
		EventType: "FreilassungErfolgt",
		Text:      "Um 15:42 Uhr lassen sich beide Papageien mit Sonnenblumenkernen in die mitgebrachte Transportbox locken. Keine Verletzten. Alle Gaeste erhalten ihre Croissants, das Haus uebernimmt die Rechnung.",
		Payload:   `{"freilassung":"ohne Widerstand","verletzte":0,"letzter_gast":"Dr. Susanne Kramer"}`,
	},
	{
		Stream:    "fall-2024-0080",
		EventType: "FahrzeugSichergestellt",
		Text:      "Transportfahrzeug im Einsatz: Lastenrad des Augsburger Zoos mit gruener Transportbox. Ausbruchsursache: Volierentuer nach Reinigung nicht korrekt verriegelt. Tierpflegeplan wird ueberarbeitet.",
		Payload:   `{"fahrzeug":"Lastenrad Zoo Augsburg","ausbruchsursache":"Voliere 7 nicht verriegelt"}`,
	},
}
