// docs-content.generated.ts
//
// AUTO-GENERATED by scripts/build-docs.ts — do not edit by hand.
// Edit the source Markdown under docs/help/ and re-run the script
// (or just `bun run dev`, which calls it via predev).

export const agent_design = `# Agent design

How the LLM is fed with the right knowledge to write correct
queries even when the data model has 100 tables and three-way
joins.

## The problem

The naive way to wire an assistant to a GraphQL endpoint is to
let the model write GraphQL directly. That falls apart fast:

- Field names get hallucinated (\`first_name\` instead of
  \`firstname\`).
- Filter syntax gets reinvented (\`{ eq: "Berlin" }\` instead of
  \`city_eq: "Berlin"\`).
- Operators show up that the schema does not implement
  (\`startsWith\`, \`>=\`).
- Joins over three or five tables go sideways.

A schema with two domains might survive this. A schema with a
hundred will not.

## The principle

> Give the model **as much information as possible** about what
> it can do, and shape the workflow so it does not have to invent
> anything.

Two layers carry the knowledge:

| Layer                  | Stored in                  | Loaded     |
|------------------------|----------------------------|------------|
| Behaviour conventions  | \`oos.oos_global_schema\`    | always     |
| Per-domain GraphQL     | \`oos.oos_domain_schema\`    | on demand  |

Both tables are populated by [oosai](./architecture.md) — every
DSL row in \`oos.domain\` and every standing-instruction prompt in
\`oos.global_prompt\` is rendered into a precise, machine-shaped
chunk and embedded with pgvector.

## The knowledge sandwich

\`\`\`
┌──────────────────────────────────────────────────────────────┐
│  ALWAYS in the system prompt — small, ~3-5 KB                 │
├──────────────────────────────────────────────────────────────┤
│  • All 10 oos_global_schema chunks                            │
│  • Domain index — one line per domain with aliases:           │
│      person — Mitarbeiter, Kunden, Kontakte                   │
│        (alias: person Liste, person Detail, alle person)      │
│      note — Notizen, gehören zu Personen                      │
│        (alias: notiz Liste, notiz Detail)                     │
│  • User context (role, language)                              │
│  • Worked examples — see below                                │
└──────────────────────────────────────────────────────────────┘
                  ↓ model decides what it needs
┌──────────────────────────────────────────────────────────────┐
│  ON-DEMAND via oos_schema_search                              │
├──────────────────────────────────────────────────────────────┤
│  • Model calls the tool with "persons by city"                │
│  • oosai returns the top-N domain chunks (typically 1-3)      │
│  • Each chunk is a complete recipe: fields, filter examples,  │
│    relations, dropdown sources, permissions, AI hints         │
└──────────────────────────────────────────────────────────────┘
                  ↓ model has the precise GraphQL
┌──────────────────────────────────────────────────────────────┐
│  EXECUTION via oos_query                                      │
├──────────────────────────────────────────────────────────────┤
│  • Model writes the GraphQL by copying from the chunk         │
│    and substituting values                                    │
│  • bun executes the query against oosgql                      │
│  • If oosgql returns an error the model sees it and retries   │
└──────────────────────────────────────────────────────────────┘
\`\`\`

## Why the sandwich, and not one of the extremes

**Extreme 1 — pump everything into the system prompt.** Works
for 5-10 domains. At 100 domains the prompt grows past the
model's effective attention span: the same prompt that gives a
3 KB schema reliably won't survive 1 MB of schema.

**Extreme 2 — pure RAG, no domain knowledge in the prompt.** The
model has no idea which domains exist when the user types
*"zeige mir alle Personen"*. It would need to guess search terms
that map to domain names. Embeddings handle this surprisingly
well, but adding a one-line index for every domain in the prompt
makes it dramatically more robust at almost no token cost.

**Sandwich — index in the prompt, full chunks on demand.** Best
of both. The model knows what exists, knows the conventions,
fetches the precise GraphQL when it needs to write something.

## What the model sees (system prompt skeleton)

\`\`\`
You are OOS Assistant. Current user: admin (role: admin).
Reply in the user's language.

# Behaviour
[10 chunks from oos.oos_global_schema:
 identity, filter_syntax, query_behavior, mutation_behavior,
 schema_discovery, dropdowns_and_meta, permissions, deletion,
 language, response_style]

# Available domains
- person — Mitarbeiter, Kunden und Kontakte. Eine Zeile pro Person.
  Aliase: person Liste, person Detail, alle person, person bearbeiten
- note — Notizen, gehören zu Personen.
  Aliase: notiz Liste, notiz Detail, alle notizen

# Example workflow

User: "Zeig mir alle Personen aus Berlin"
1. oos_schema_search(query="person")  → exact GraphQL chunk
2. Find the example:
     Filter example (city equals): { person(city_eq: "value") { ... } }
3. oos_query with { person(city_eq: "Berlin") { id firstname ... } }
4. Reply briefly: "Hier sind alle Personen aus Berlin."

User: "Alle Personen mit ihren Notizen"
1. oos_schema_search(query="person")
2. In the chunk, see "Relations: notes (has_many note, id -> person_id)"
3. oos_schema_search(query="note")
4. Combine into one query:
     { person { id firstname lastname notes { id title body } } }
5. oos_query, then answer.
\`\`\`

The worked examples are the key. They show the workflow as a
concrete recipe the model can pattern-match against. With them
the success rate on novel queries climbs from "occasional" to
"reliable".

## Tools

Two tools are enough for read-only operation:

\`\`\`ts
oos_schema_search({ query: string, n?: number })
  -> { chunks: [{ context_name: string, chunk: string }] }

oos_query({ context_name: string, query: string })
  -> { data: any, error?: string }
\`\`\`

\`oos_query\` returns the raw GraphQL response. The model writes a
short user-facing reply, and bun streams a tab-open event to the
mainview alongside, so the result renders next to the chat.

Mutation tools come later:

\`\`\`ts
oos_save({ context_name: string, data: object })
  -> { id: number, error?: string }

oos_delete({ context_name: string, id: number })
  -> { ok: true, error?: string }
\`\`\`

\`oos_save\` does **not** ask the model to write a GraphQL mutation.
It calls
[\`buildMutationFromMap\`](https://github.com/onisin/onisin/blob/main/packages/oos-gql-ts/src/client/build-mutation.ts)
internally — same principle as everywhere else: let the model
shape the data, let deterministic code shape the syntax.

## The loop

Plain ReAct. Bun owns it; no framework.

\`\`\`ts
const messages = [systemPrompt, ...history, userMessage];
let step = 0;
while (step++ < MAX_STEPS) {
    const resp = await openai.chat.completions.create({
        model, messages, tools,
    });
    const msg = resp.choices[0].message;
    messages.push(msg);
    if (!msg.tool_calls?.length) {
        return msg.content;          // final answer
    }
    for (const call of msg.tool_calls) {
        const result = await runTool(call.function.name,
                                     JSON.parse(call.function.arguments));
        messages.push({
            role: "tool",
            tool_call_id: call.id,
            content: JSON.stringify(result),
        });
        emit("tool", { name: call.function.name, result });   // to UI
    }
}
\`\`\`

\`MAX_STEPS = 8\` is enough. A typical query is two steps
(\`oos_schema_search\`, \`oos_query\`); a join is three or four. If
the model is still calling tools at step 8 something is wrong
with the prompt, not the loop.

## Streaming events to the mainview

Each phase of the loop emits a typed event the UI can react to:

- \`assistant_text_chunk\` — partial completion text (during
  streamed final answer).
- \`tool_call_start\` — tool name + arguments. Frontend renders an
  inline collapsed card under the assistant bubble.
- \`tool_call_end\` — short summary of the result. Card updates
  in place.
- \`tab_open\` — one of the tools (\`oos_query\`, future \`oos_get\`)
  produced a renderable result. Frontend opens or refocuses the
  tab and feeds the data into the renderer.

## What we do not need

- **A framework.** The agent loop is 80 lines. Eino was a Go
  abstraction over the same idea; the TS equivalent is a
  \`while\` loop. Adding LangChain or Vercel AI SDK is more
  surface area than value.
- **Function-arg-as-GraphQL.** The model never writes GraphQL
  for mutations — \`oos_save\` takes a data object. It writes
  GraphQL for queries only because the schema chunks contain
  ready-made examples it can copy verbatim.
- **A Mega-\`oos_query\` covering everything.** Two read tools is
  the floor; we add one more tool only if a benchmark shows
  the current set is producing wrong queries.
`;

export const architecture = `# Architecture

Three runtime processes plus IndexedDB for persistence. Nothing
exotic — every piece either ships as a Bun app or is a service
the user already has running.

\`\`\`
┌────────────────────────────────────────────────────────────┐
│                      oos (Electrobun app)                   │
│                                                             │
│  ┌──────────────────────┐         ┌────────────────────┐   │
│  │   mainview (React)   │  RPC    │    bun backend     │   │
│  │                      │◄───────►│                    │   │
│  │  Chat · Tabs · UI    │         │  Tool loop · LLM   │   │
│  │  IndexedDB (Dexie)   │         │  HTTP gateway      │   │
│  └──────────────────────┘         └─────────┬──────────┘   │
│                                              │              │
└──────────────────────────────────────────────┼──────────────┘
                                               │
                ┌──────────────────────────────┼─────────┐
                ▼                              ▼         ▼
        ┌──────────────┐              ┌────────────┐ ┌────────────┐
        │ LLM endpoint │              │  oosgql    │ │   oosai    │
        │ (OpenAI-API) │              │ /query     │ │ /search    │
        │ Ollama, vLLM │              │ /mutation  │ │ /global    │
        └──────────────┘              └─────┬──────┘ └─────┬──────┘
                                            │              │
                                            ▼              ▼
                                       ┌────────────────────────┐
                                       │       Postgres         │
                                       │  oos.* + public.*      │
                                       │  pgvector embeddings   │
                                       └────────────────────────┘
\`\`\`

## mainview

A single React app rendered by Electrobun's webview. Mantine
[AppShell](https://mantine.dev/core/app-shell/) for layout: a thin
header, the chat on the left, a vertical tab rail in the middle,
the active tab content on the right, a slim status footer.

Persistence lives in IndexedDB via [Dexie](https://dexie.org). One
database, one settings table for now — the Tab state will join it
once the assistant starts opening tabs as a side effect of tool
calls.

## bun backend

The bun process is the HTTP gateway *and* the tool loop. Every
external call (LLM completion, \`oosgql\`, \`oosai\`) goes through here
for two reasons:

- **No CORS pain.** Local Ollama and vLLM reject browser-origin
  fetch by default. Server-to-server fetch is unaffected. Same
  with most cloud OpenAI-compatible endpoints behind a proxy.
- **Secrets stay out of the renderer bundle.** The API key sits
  in the bun process; the webview never sees it.

The mainview talks to bun through Electrobun's typed RPC. One
schema (\`OosRPC\` in \`src/bun/index.ts\`), one Electroview client
(\`src/mainview/rpc.ts\`).

## oosgql

GraphQL over the OOS domain model. The schema is built at startup
from the \`oos.domain\` rows (one DSL definition per domain) by
[oos-gql-ts](https://github.com/onisin/onisin) and rebuilt on a
\`LISTEN/NOTIFY\` whenever the table changes. Two endpoints:

- \`POST /query\` — reads, no auth check beyond what the schema
  exposes.
- \`POST /mutation\` — writes, gated by the \`X-OOS-Group\` header
  against the per-domain permission matrix.

The query language is GraphQL but with a deliberate twist: filter
arguments are flat suffixes (\`age_gt\`, \`city_eq\`, \`firstname_like\`)
rather than nested \`where\` blocks. This keeps queries short and
unambiguous, especially for an LLM writing them.

## oosai

The retrieval layer. Bun-Hono service with three endpoints:

- \`POST /search\` — embed a query string and return the top-N
  closest \`oos.oos_domain_schema\` rows by cosine distance. The
  agent's \`oos_schema_search\` tool is a thin wrapper around this.
- \`GET /global\` — return every standing-instruction prompt from
  \`oos.oos_global_schema\`. Loaded once at session start, prepended
  to the system prompt.
- \`POST /reindex\` — manual trigger to rebuild the embedding tables.

Embeddings come from a configurable Ollama model
(\`granite-embedding:latest\` by default).

## Postgres

Two schemas:

- \`public\` — the user-owned tables (person, note, …).
- \`oos\` — system-owned: \`domain\`, \`view\`, \`global_prompt\`,
  \`event_mappings\`, plus the embedding tables \`oos_domain_schema\`
  and \`oos_global_schema\` populated by the oosai backfill.

\`pgvector\` is mandatory; embeddings are 384-dimensional.

## Why this split

A previous version had everything in one Go binary. It worked but
made every change a full rebuild, and the LLM-facing surface was
buried inside a desktop app's runtime. Splitting \`oosgql\` and
\`oosai\` out into Bun services means each one is a 3-second restart
and can be tested with \`curl\`. The Electrobun client is then just
a UI — no embedded server, no plugin loader, no surprises.
`;

export const finetuning = `# Finetuning

Each LLM model has its own row of fine-tuning values. Switching
the chat model in \`Connection → Chat model\` automatically reloads
the matching row in this panel.

## The four levers

| Field         | What it does                                        |
|---------------|-----------------------------------------------------|
| Temperature   | How creative the LLM is allowed to be. 0 is        |
|               | deterministic (same input → same output), 1 is     |
|               | balanced, >1 is experimental. RAG workflows want   |
|               | this low — the LLM should pull facts out of the    |
|               | retrieved context, not invent them.                |
| Timeout       | How long the agent waits for one chat-completion   |
|               | call before giving up. Format: \`30s\`, \`5m\`,        |
|               | \`10m\`, \`1h\`.                                       |
| Max tokens    | Upper bound on the LLM's response length.          |
|               | Smaller models drift on long generations — keep    |
|               | this lower for them.                               |
| Top hits      | How many schema chunks \`oos_schema_search\`         |
|               | returns to the LLM per tool call. More hits =      |
|               | richer context but a larger prompt and more        |
|               | room for the model to lose focus.                  |

## Cloud vs Local presets

The dropdown at the top of the panel sets all four fields to a
named starting point. Pick whichever matches your endpoint, then
tweak from there. The selector never persists on its own — Save
is what writes the row.

### Cloud

Use this for OpenAI, Anthropic (via a proxy), Groq, Together,
Fireworks, and any other hosted provider.

| Field         | Value     |
|---------------|-----------|
| Temperature   | 0.20      |
| Timeout       | 5m        |
| Max tokens    | 4096      |
| Top hits      | 10        |

The long timeout reflects that hosted endpoints can stall under
load and we'd rather wait than fail. Big max-tokens is fine
because cloud models stay coherent over long generations and
their per-token cost makes long answers a deliberate choice, not
an accident.

### Local

Use this for Ollama, vLLM, llama.cpp, LM Studio — anything you
run on the workstation itself.

| Field         | Value     |
|---------------|-----------|
| Temperature   | 0.20      |
| Timeout       | 90s       |
| Max tokens    | 1024      |
| Top hits      | 10        |

The shorter timeout matters: a stalled local model should fail
fast so the agent loop can recover, instead of blocking the
whole UI for five minutes. The smaller max-tokens reflects that
7–14 B-parameter models drift into incoherent text on long
generations — capping the response keeps answers tight and
cheap to regenerate.

If your workstation comfortably runs a 32 B+ model, you may
want a hybrid: local timeout (90s) but cloud-style max-tokens
(4096). Just pick Local in the preset and bump max-tokens up.

## Why per-model

Different models have different needs:

- A small code-focused model like Phi-4-mini or Qwen2.5-Coder-7B
  benefits from low temperature and short responses — it should
  emit a single well-formed GraphQL query, not a paragraph of
  reasoning.
- A larger conversational model can run at the same temperature
  but tolerate longer answers without drifting.
- Cloud models (Claude, GPT-4o) handle high temperature and long
  context without much risk.

Storing settings per model means switching from a small local
model to a hosted Claude doesn't require re-tuning by hand every
time.

## Where the data lives

| Setting              | Storage                                  |
|----------------------|------------------------------------------|
| One row per model    | IndexedDB \`oos.settings.finetuning:<id>\` |
| Defaults             | \`DEFAULT_FINETUNING\` in finetuning.ts    |
| Presets              | \`FINETUNING_PRESETS\` in finetuning.ts    |

Resetting a model uses \`Auf Defaults zurücksetzen\` — that
deletes the row and a future load falls back to the cloud
preset (the historical default).
`;

export const index = `# oos — chat-driven dynamic UI

Welcome to oos. This is the user-facing OOS app: one chat window
that talks to an LLM, plus a tab area that fills with the views
the assistant opens for you.

## What it does

You type a question in plain language. The assistant:

1. Looks up which OOS domains are relevant.
2. Builds a GraphQL query against [oosgql](./architecture.md).
3. Opens the result as a tab on the right.

You then read, filter, edit, save. All of that runs through the
same dynamic-rendering pipeline driven by the OOS DSL — the
domain definitions and views that live in the \`oos.domain\` and
\`oos.view\` tables.

## Topics

- **[Architecture](./architecture.md)** — how the pieces fit
  together. Mainview, bun backend, IndexedDB, oosgql, oosai.
- **[Agent design](./agent-design.md)** — how the LLM is fed
  with the right knowledge to write correct queries even when
  the data model has 100 tables and three-way joins.
- **[Settings](./settings.md)** — where the LLM endpoint and
  service URLs are configured. Persisted in IndexedDB.
- **[Keyboard shortcuts](./shortcuts.md)** — what you can do
  without reaching for the mouse.

## Conventions

This app is the spiritual successor of the earlier \`oos_old\`
Go/Fyne client. It keeps the patterns that worked there — the
agent's tool vocabulary, the global standing-instructions in the
system prompt, the schema-chunk RAG approach — and drops the
patterns that did not: the separate dashboard window, the AI
assistant as a side panel, the explicit Board / Events mode
switch. There is one window, one chat, and a tab strip for
whatever the assistant opens.
`;

export const settings = `# Settings

Open with \`⌘ ,\` or via the burger menu.

All settings are persisted in IndexedDB under the database name
\`oos\`, table \`settings\`, key \`app\`. There is no file written
anywhere on disk by oos itself — same code path will work
identically when the app eventually runs in a browser tab.

## Connection settings

| Field           | What it does                                  |
|-----------------|-----------------------------------------------|
| LLM base URL    | OpenAI-compatible endpoint. The footer pings  |
|                 | this every 15 seconds.                        |
| API key         | Bearer token sent with every LLM request.     |
|                 | Local endpoints accept any non-empty string;  |
|                 | leave blank to send the literal "ollama".     |
| Chat model      | Picked from the model list returned by        |
|                 | \`GET /v1/models\` on the configured endpoint.  |
| oosgql URL      | Where to send GraphQL queries. Defaults to    |
|                 | \`http://localhost:4000\`.                      |
| oosai URL       | Where to send \`oos_schema_search\` and load    |
|                 | the standing-instructions from. Defaults to   |
|                 | \`http://localhost:4100\`.                      |

## Why everything is OpenAI-compatible

There is exactly one HTTP shape we send to the LLM:
\`POST /v1/chat/completions\` with the standard message + tools
payload. Every modern provider speaks it: Ollama, vLLM, OpenAI,
Anthropic via a proxy like LiteLLM or cLLM, Groq, Together,
fireworks. Switching providers is a URL change.

The same goes for \`GET /v1/models\` — the dropdown in Settings
populates from whatever the configured endpoint reports, no
provider-specific code paths.

## Why all of this is routed through bun

The model picker, the agent loop, every external HTTP call
goes through the bun process rather than \`fetch\` from the
webview. Two reasons:

1. **CORS.** Local Ollama and vLLM reject browser-origin
   requests by default. Server-to-server fetch is unaffected.
2. **Secrets.** The API key never reaches the renderer-side
   bundle; it sits in the bun process and is read fresh per
   request.

The mainview talks to bun through Electrobun's typed RPC. See
\`src/bun/index.ts\` for the shape and \`src/mainview/rpc.ts\` for
the client.

## Where the data lives

| Setting           | Storage                                     |
|-------------------|---------------------------------------------|
| Connection fields | IndexedDB \`oos.settings.app\`               |
| Open tabs         | (mainview React state — not persisted yet) |
| Chat history      | (mainview React state — not persisted yet) |

Tab and chat persistence will move into IndexedDB once the
shapes settle. The plan is one row per session, plus an
ephemeral autosave for the in-progress draft.
`;

export const shortcuts = `# Keyboard shortcuts

\`mod\` is \`⌘\` on macOS, \`Ctrl\` everywhere else.

## Global

| Shortcut  | What it does            |
|-----------|-------------------------|
| \`⌘ ,\`     | Toggle Settings drawer  |

## Chat input

| Shortcut         | What it does                  |
|------------------|-------------------------------|
| \`Enter\`          | Send the message              |
| \`Shift + Enter\`  | Newline inside the message    |

## Planned

| Shortcut  | What it will do                                  |
|-----------|--------------------------------------------------|
| \`⌘ K\`     | Tab switcher (à la VS Code's command palette)    |
| \`⌘ W\`     | Close active tab                                 |
| \`⌘ /\`     | Focus the chat input from anywhere               |
| \`⌘ N\`     | New tab via the LLM (empty-state landing page)   |

These are not wired yet — they show up here as a reminder of
what muscle memory we are building toward.
`;
export const docsContent: Record<string, string> = {
	"agent-design": agent_design,
	"architecture": architecture,
	"finetuning": finetuning,
	"index": index,
	"settings": settings,
	"shortcuts": shortcuts,
};
